# Generated by Django 2.2.3 on 2019-07-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0005_auto_20190731_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('instname', models.CharField(max_length=50)),
            ],
        ),
    ]
